# SELECT
#     ITEM_ID,
#     ITEM_NAME,
#     RARITY
# FROM ITEM_INFO
# WHERE ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
# ORDER BY ITEM_ID DESC;

# 조인으로도 풀어보기
SELECT
    i.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM ITEM_INFO i
LEFT JOIN ITEM_TREE t
    ON i.ITEM_ID = t.PARENT_ITEM_ID
WHERE t.PARENT_ITEM_ID IS NULL
ORDER BY i.ITEM_ID DESC;