SELECT
    c.CAR_ID,
    c.CAR_TYPE,
    ROUND(c.DAILY_FEE * 30 * (100 - IFNULL(d.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS d
    ON c.CAR_TYPE = d.CAR_TYPE
   AND d.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND NOT EXISTS (
      SELECT 1
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
      WHERE h.CAR_ID = c.CAR_ID
        AND h.START_DATE <= '2022-11-30'
        AND h.END_DATE >= '2022-11-01'
  )
  AND ROUND(c.DAILY_FEE * 30 * (100 - IFNULL(d.DISCOUNT_RATE, 0)) / 100)
      BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;