WITH AVALIABLE_CAR AS (
    SELECT 
        c.CAR_ID,
        c.CAR_TYPE,
        c.DAILY_FEE
    FROM
        CAR_RENTAL_COMPANY_CAR AS c
    WHERE
        c.CAR_TYPE IN ('세단', 'SUV')
        AND NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
            WHERE 
                c.CAR_ID = h.CAR_ID
                AND h.START_DATE <= '2022-11-30'
                AND h.END_DATE >= '2022-11-01'
        )
)

SELECT
    a.CAR_ID,
    a.CAR_TYPE,
    ROUND(a.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) AS FEE
FROM AVALIABLE_CAR AS a
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS d
    ON a.CAR_TYPE = d.CAR_TYPE
WHERE d.DURATION_TYPE = '30일 이상'
    AND ROUND(a.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) >= 500000 
    AND ROUND(a.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, a.CAR_TYPE ASC, a.CAR_ID DESC;