SELECT 
    e.ID,
    CASE
        # 현재 레코드보다 값이 큰 레코드 개수를 파악 -> 현재 레코드의 순위 파악
        WHEN (SELECT COUNT(*) FROM ECOLI_DATA WHERE SIZE_OF_COLONY > e.SIZE_OF_COLONY) + 1 <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.25 THEN 'CRITICAL'
        WHEN (SELECT COUNT(*) FROM ECOLI_DATA WHERE SIZE_OF_COLONY > e.SIZE_OF_COLONY) + 1 <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.50 THEN 'HIGH'
        WHEN (SELECT COUNT(*) FROM ECOLI_DATA WHERE SIZE_OF_COLONY > e.SIZE_OF_COLONY) + 1 <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA e
ORDER BY e.ID