SELECT 
    e.ID,
    CASE 
        WHEN (SELECT COUNT(*) FROM ECOLI_DATA WHERE SIZE_OF_COLONY > e.SIZE_OF_COLONY) < (SELECT COUNT(*) FROM ECOLI_DATA) * 0.25 THEN 'CRITICAL'
        WHEN (SELECT COUNT(*) FROM ECOLI_DATA WHERE SIZE_OF_COLONY > e.SIZE_OF_COLONY) < (SELECT COUNT(*) FROM ECOLI_DATA) * 0.50 THEN 'HIGH'
        WHEN (SELECT COUNT(*) FROM ECOLI_DATA WHERE SIZE_OF_COLONY > e.SIZE_OF_COLONY) < (SELECT COUNT(*) FROM ECOLI_DATA) * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA e
ORDER BY e.ID;