# SELECT *
# FROM PLACES
# WHERE HOST_ID IN (
#     SELECT HOST_ID
#     FROM PLACES
#     GROUP BY HOST_ID
#     HAVING COUNT(*) >= 2
# )
# ORDER BY ID ASC;


SELECT p.*
FROM PLACES p
JOIN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
) heavy_users
ON p.HOST_ID = heavy_users.HOST_ID
ORDER BY p.ID ASC;