SELECT
    h.HISTORY_ID,
    ROUND(c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (100 - IFNULL(d.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
JOIN CAR_RENTAL_COMPANY_CAR AS c
    ON h.CAR_ID = c.CAR_ID
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS d
    ON c.CAR_TYPE = d.CAR_TYPE
        AND (
            (DATEDIFF(h.END_DATE, h.START_DATE) + 1) >= 90 AND d.DURATION_TYPE = '90일 이상'
            OR (DATEDIFF(h.END_DATE, h.START_DATE) + 1) BETWEEN 30 AND 89 AND d.DURATION_TYPE = '30일 이상'
            OR (DATEDIFF(h.END_DATE, h.START_DATE) + 1) BETWEEN 7 AND 29 AND  d.DURATION_TYPE = '7일 이상'
        )
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;