SELECT
    j.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) AS j
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF GROUP BY FLAVOR) AS h
    ON j.FLAVOR = h.FLAVOR
GROUP BY j.FLAVOR
ORDER BY j.TOTAL_ORDER + h.TOTAL_ORDER DESC
LIMIT 3;