SELECT
    u.USER_ID,
    u.NICKNAME,
    SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS u
JOIN (SELECT * FROM USED_GOODS_BOARD WHERE STATUS = 'DONE') AS b
    ON u.USER_ID = b.WRITER_ID
GROUP BY u.USER_ID, u.NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;