# SQL의 실행 순서
# 1.	FROM → 2. WHERE → 3. SELECT → 4. GROUP BY → 5. HAVING → 6. ORDER BY

# +0으로 문자열을 숫자로 자동 형변환 / 09가 9로 변환됨

SELECT
    DATE_FORMAT(DATETIME, '%H') + 0 AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') + 0 BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR;