SELECT b.ITEM_ID, b.ITEM_NAME, b.RARITY FROM ITEM_TREE AS a
LEFT JOIN ITEM_INFO AS b ON b.ITEM_ID = a.ITEM_ID
WHERE PARENT_ITEM_ID NOT IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY <> 'RARE')
ORDER BY ITEM_ID DESC