SELECT
    MONTH(a.START_DATE) AS MONTH,
    a.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS a
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5) AS b
    ON a.CAR_ID = b.CAR_ID
WHERE a.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY a.CAR_ID, MONTH(a.START_DATE)
HAVING RECORDS >= 1
ORDER BY MONTH ASC, a.CAR_ID DESC;
