SELECT
    e.YEAR AS YEAR,
    e.YEAR_MAX - d.SIZE_OF_COLONY AS YEAR_DEV,
    d.ID AS ID
FROM (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS YEAR_MAX
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS e
JOIN ECOLI_DATA AS d
    ON e.YEAR = YEAR(d.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV