SELECT 
    fh.FLAVOR
FROM FIRST_HALF AS fh
LEFT JOIN 
    ICECREAM_INFO AS i
    ON fh.FLAVOR = i.FLAVOR
WHERE
    fh.TOTAL_ORDER > 3000
    AND i.INGREDIENT_TYPE = 'fruit_based'
ORDER BY fh.TOTAL_ORDER DESC;