SELECT
    i.ingredient_type AS INGREDIENT_TYPE,
    SUM(o.total_order) AS TOTAL_ORDER
FROM FIRST_HALF AS o
INNER JOIN ICECREAM_INFO AS i ON o.flavor = i.flavor
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;