SELECT
    a.CATEGORY,
    a.PRICE AS MAX_PRICE,
    a.PRODUCT_NAME
FROM FOOD_PRODUCT a
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE CATEGORY = a.CATEGORY)
ORDER BY MAX_PRICE DESC;