WITH
FE AS (
  SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'
),
PYTHON AS (
  SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'
),
CSHARP AS (
  SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'
)

SELECT
  CASE
    WHEN d.SKILL_CODE & fe.CODE > 0 AND d.SKILL_CODE & py.CODE > 0 THEN 'A'
    WHEN d.SKILL_CODE & cs.CODE > 0 THEN 'B'
    WHEN d.SKILL_CODE & fe.CODE > 0 THEN 'C'
  END AS GRADE,
  d.ID,
  d.EMAIL
FROM DEVELOPERS d
CROSS JOIN FE fe
CROSS JOIN PYTHON py
CROSS JOIN CSHARP cs
WHERE # CASE에 걸리지 않는, 등급이 없는 개발자 거르기
  (d.SKILL_CODE & fe.CODE > 0 AND d.SKILL_CODE & py.CODE > 0)
  OR (d.SKILL_CODE & cs.CODE > 0)
  OR (d.SKILL_CODE & fe.CODE > 0)
ORDER BY GRADE, ID;